# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
  export ZSH="/home/haha/.oh-my-zsh"

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to load
# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

. /usr/share/autojump/autojump.sh

#proxy_url=http://127.0.0.1:8118
proxy_url=http://192.168.81.1:1080
alias proxy="export http_proxy=${proxy_url} https_proxy=${proxy_url}"
alias unproxy="unset http_proxy https_proxy"

export BAKE_HOME="/home/haha/ns3-dev-workspace/bake"
export PATH=$PATH:$BAKE_HOME
export PYTHONPATH=$PYTHONPATH:$BAKE_HOME

# NS3
export NS3DIR="/home/haha/ns3.29-dev-workspace/ns-3-allinone/ns-3-dev"
# export NS3CONFIG="--enable-sudo --enable-examples --enable-tests"
export NS3CONFIG="--enable-examples --enable-tests"
#export NS3DEBUG="--build-profile=debug"
#export NS3OPTIMIZED="--build-profile=optimized"
export NS3DEBUG="--build-profile=debug --out=build/debug"
export NS3OPTIMIZED="--build-profile=optimized --out=build/optimized"

# JAVA ENV
export JAVA_HOME="/home/haha/jdk1.8.0_161"
export JRE_HOME=$JAVA_HOME/jre
export CLASSPATH=.:$JAVA_HOME/lib:$JRE_HOME/lib:$CLASSPATH
export PATH=$JAVA_HOME/bin:$JRE_HOME/bin:$PATH

# NS2
export PATH="$PATH:/home/haha/ns-allinone-2.35/bin:/home/haha/ns-allinone-2.35/tcl8.5.10/unix:/home/haha/ns-allinone-2.35/tk8.5.10/unix"
#export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/home/haha/ns-allinone-2.35/otcl-1.14:/home/haha/ns-allinone-2.35/lib:/home/haha/fuzzylite/release/bin/"
export TCL_LIBRARY="$TCL_LIBRARY:/home/haha/ns-allinone-2.35/tcl8.5.10/library"

# Matlab Runtime
LIBRARY_PATH_OLD=${LIBRARY_PATH}
LD_LIBRARY_PATH_OLD=${LD_LIBRARY_PATH}
C_INCLUDE_PATH_OLD=${C_INCLUDE_PATH}
CPLUS_INCLUDE_PATH_OLD=${CPLUS_INCLUDE_PATH}
#export LIBRARY_PATH="${LIBRARY_PATH}:/home/haha/ns3.29-dev-workspace/ns-3-allinone/ns-3-dev/libdir/lib:/usr/local/MATLAB/MATLAB_Runtime/v94/runtime/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v94/bin/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v94/sys/os/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v94/extern/bin/glnxa64"
#export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/home/haha/ns3.29-dev-workspace/ns-3-allinone/ns-3-dev/libdir/lib:/usr/local/MATLAB/MATLAB_Runtime/v94/runtime/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v94/bin/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v94/sys/os/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v94/extern/bin/glnxa64"
#export C_INCLUDE_PATH="${C_INCLUDE_PATH}:/usr/local/MATLAB/MATLAB_Runtime/v94/extern/include"
#export CPLUS_INCLUDE_PATH="${CPLUS_INCLUDE_PATH}:/usr/local/MATLAB/MATLAB_Runtime/v94/extern/include"

alias matlab_runtime="export LIBRARY_PATH=${LIBRARY_PATH}:/home/haha/ns3.29-dev-workspace/ns-3-allinone/ns-3-dev/libdir/lib:/usr/local/MATLAB/MATLAB_Runtime/v94/runtime/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v94/bin/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v94/sys/os/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v94/extern/bin/glnxa64 \
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/haha/ns3.29-dev-workspace/ns-3-allinone/ns-3-dev/libdir/lib:/usr/local/MATLAB/MATLAB_Runtime/v94/runtime/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v94/bin/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v94/sys/os/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v94/extern/bin/glnxa64 \
export C_INCLUDE_PATH=${C_INCLUDE_PATH}:/usr/local/MATLAB/MATLAB_Runtime/v94/extern/include \
export CPLUS_INCLUDE_PATH=${CPLUS_INCLUDE_PATH}:/usr/local/MATLAB/MATLAB_Runtime/v94/extern/include"
alias unmatlab_runtime="export LIBRARY_PATH=${LIBRARY_PATH_OLD} \
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH_OLD} \
export C_INCLUDE_PATH=${C_INCLUDE_PATH_OLD} \
export CPLUS_INCLUDE_PATH=${CPLUS_INCLUDE_PATH_OLD}"

matlab_runtime

# SUMO_HOME
export SUMO_HOME="/home/haha/sumo-0.32.0"
